### ISSUE TITLE
Weather doesnt seem to be generated?

### ISSUE THREAD

**Issue by gjm19761** [liam8888999/ErsatzTV-Filler#39]
Im in UK and wttr.in picks up my location fine (Tidworth , UK) however if i put Tidworth in my city in the config and UK as state or change it to tidworth UK etc, the weather doesnt generate, it seems fine for U.S cities but not UK?

**Comment by liam8888999** [comment]
There is an issue with the image not being shown if that is what you are referring to. However you should get text instead that shows the weather info. 
Can you post the ersatztv filler ffmpeg log. Can be downloaded within the logs page on the ui

**Comment by liam8888999** [comment]
Also have you tried Wiltshire as the state. The Etta.in site seems to be a bit broken at the moment though

**Comment by gjm19761** [comment]
seems it ,might work, does it get pics thru https://wttr.in/ ?

altough the fallback weather is saying correct info but it fails at ffmpeg ;

2023-10-22 18:01:52 | error: Error running weather fallback command: Command failed: "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\ffmpeg\ffmpeg-windows.exe" -y -f lavfi -i color=000000:1280x720 -stream_loop -1 -i "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\14.mp3" -shortest -filter_complex "[0:v]drawtext=text='
                      Unfortunately the weather filler is unavailable at this time,

                      Hopefully it will be back soon

                      The Current Temperature is 15°C or 59°F

                      The Current Humidity 63percent

                      It is Currently Sunny outside
                    ':x=(W-tw)/2:y=(H-th)/2:fontsize=24:fontcolor=white[bg]" -map "[bg]" -map 1:a -c:v libx264 -c:a copy -t 25 weather-v3.mp4
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Trailing option(s) found in the command: may be ignored.
Input #0, lavfi, from 'color=000000:1280x720':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
Input #1, mp3, from 'C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\14.mp3':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:30.04, start: 0.025057, bitrate: 128 kb/s
  Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91
Fontconfig error: Cannot load default config file: No such file: (null)
[Parsed_drawtext_0 @ 000001461e140800] Using "C:/Windows/fonts\times.ttf"
Filter drawtext:default has an unconnected output

**Comment by liam8888999** [comment]
yes, it does get pics from wttr.in but the oicture renderer on that site is down/being fixed which is why it is using the fallback, the fallback does appear to be broken on windows though, i think i will need to change from drawtext to subtitle for the video which will take at least a few days

**Comment by liam8888999** [comment]
hopefully fixed https://github.com/liam8888999/ErsatzTV-Filler/releases/tag/V1.5.3

**Comment by gjm19761** [comment]
nope ...

2023-10-23 23:14:32 | error: Error running weather fallback command: Command failed: "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\ffmpeg\ffmpeg-windows.exe" -y -f lavfi -i color=000000:1280x720 -stream_loop -1 -i "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\31.mp3" -shortest -filter_complex "[0:v]drawtext=textfile='C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\workdir\Weather\error.txt':x=(W-tw)/2:y=(H-th)/2:fontsize=24:fontcolor=white[bg]" -map "[bg]" -map 1:a -c:v libx264 -c:a copy -t 25 weather-v3.mp4
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, lavfi, from 'color=000000:1280x720':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
Input #1, mp3, from 'C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\31.mp3':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:30.04, start: 0.025057, bitrate: 128 kb/s
  Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91
[Parsed_drawtext_0 @ 00000255675e3500] Both text and text file provided. Please provide only one
[AVFilterGraph @ 00000255675e1580] Error initializing filters
Error initializing complex filters.
Invalid argument

**Comment by gjm19761** [comment]
get his beforehand which is why it falls back;

2023-10-23 23:14:32 | error: Error running weather fallback command: Command failed: "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\ffmpeg\ffmpeg-windows.exe" -y -f lavfi -i color=000000:1280x720 -stream_loop -1 -i "C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\31.mp3" -shortest -filter_complex "[0:v]drawtext=textfile='C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\workdir\Weather\error.txt':x=(W-tw)/2:y=(H-th)/2:fontsize=24:fontcolor=white[bg]" -map "[bg]" -map 1:a -c:v libx264 -c:a copy -t 25 weather-v3.mp4
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, lavfi, from 'color=000000:1280x720':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 25 tbn
Input #1, mp3, from 'C:\Users\gavin\Downloads\ersatztv-filler-windows-1.5.2\resources\audio-fallback\31.mp3':
  Metadata:
    encoder         : Lavf58.45.100
  Duration: 00:00:30.04, start: 0.025057, bitrate: 128 kb/s
  Stream #1:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91
[Parsed_drawtext_0 @ 00000255675e3500] Both text and text file provided. Please provide only one
[AVFilterGraph @ 00000255675e1580] Error initializing filters
Error initializing complex filters.
Invalid argument

**Comment by liam8888999** [comment]
did you update to 1.5.3

**Comment by gjm19761** [comment]
yes thats the new output

**Comment by liam8888999** [comment]
I released 1.5.4 earlier today if you can test that

**Comment by gjm19761** [comment]
ok updated and do get a small weather mp4 saying current temp and humidity in the fallback.

is there anyway you could add to that at the top like the news, a custom header?

**Comment by liam8888999** [comment]
> ok updated and do get a small weather mp4 saying current temp and humidity in the fallback.
> 
> is there anyway you could add to that at the top like the news, a custom header? and possibly date/time generated on the bottom? so we know its being updated.

I certainly can, I also found a new weather template I hope to start using shortly.
also I am normally quicker to respond to issues/questions/feature requests on discord as I am there more often

**Comment by gjm19761** [comment]
that would be cool thanks

**Comment by liam8888999** [comment]
https://github.com/liam8888999/ErsatzTV-Filler/releases/tag/V1.6.1 includes the header and date

**Comment by gjm19761** [comment]
Thanks for the addition, changing the font to look like the news font would be good to make things more uniform.

**Comment by liam8888999** [comment]
I will look into it, currently it only uses the default font so it is strange that it uses something different On 26 Oct 2023, at 11:08 pm, gjm19761 ***@***.***> wrote:﻿
Thanks for the addition, changing the font to look like the news font would be good to make things more uniform.
